version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: certificategeneratorwebbackend
    container_name: certificate-backend
    ports:
      - 5000:5000
    networks:
      - db-net
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: certificategeneratorwebfrontend
    container_name: certificate-frontend
    ports:
      - 3000:3000
    networks:
      - db-net
networks:
  db-net:
    driver: bridge
