version: 2.1

orbs:
  docker: circleci/docker@0.5.13

jobs:
  run_tests:
    working_directory: ~/react-app
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
<<<<<<< HEAD
          command: 'sudo npm install -g'
=======
          command: "sudo npm install -g"
>>>>>>> 0fea13f8b37944fa7d461ff13c5a60a51e578235
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: sudo npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      # - run:
      # name: test
      # command: npm test

workflows:
  version: 2
  build_deploy:
    jobs:
      - run_tests
      - docker/publish:
          image: codak77/cicd
          dockerfile: dockerfile
          requires:
            - run_tests
          filters:
            branches:
              only:
<<<<<<< HEAD
                - main
=======
                - dev
>>>>>>> 0fea13f8b37944fa7d461ff13c5a60a51e578235
