version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16.10.0
      - image: docker:17.09.1-ce-git
    steps:
      - checkout # pulls code from github repo
      - setup_remote_docker
      - run: sudo npm i npm@7.24.0 -g
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Node Install
          command: |
            npm cache clear --force
            sudo npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules && ./frontend/node_modules
      # - run: npm run test
      # build the docker image on success
      - run:
          name: Docker
          when: on_success
          command: |
            docker --version
            docker login -u=$DOCKER_LOGIN -p=$DOCKER_PASSWORD
            docker build -t codak77/certificategenerator.web:$CIRCLE_BRANCH --build-arg codak77=certificategenerator.web-$CIRCLE_BRANCH .
            docker push codak77/certificategenerator.web:$CIRCLE_BRANCH
            echo "Docker build made sucessfully!! for certificategenerator.web $CIRCLE_BRANCH"
      - run:
          name: Build Failure
          when: on_fail
          command: |
            echo "ERROR building certificategenerator.web $CIRCLE_BRANCH"

workflows:
  default:
    jobs:
      - build
